### ISSUE TITLE
对于编码方式有些不理解

### ISSUE THREAD

**Issue by tangarfff** [Juzhan/TAP-Net#1]
![image](https://user-images.githubusercontent.com/77969537/119937373-3b53bd80-bfbd-11eb-9976-8eb527e12def.png)

您好，关于编码方式有点不理解的地方。
以2D为例，为什么开始所有箱子的原始状态的LAB和RAB都设置成为了0，而旋转之后的LAB和RAB都根据正常的约束来设置。

看到data.md中解释说的是 data 1 block array (after flattened) of rotation state 1, since rotation state 1 (original state) doesn't need to grasp from right size of block, we don't need to consider about its right block state。为什么original state不需要从左右两边抓取呢？指的是机器抓取时，第一步只能从箱子的top开始抓吗？

**Comment by Juzhan** [comment]
当前箱子能否抓取我们是根据 `TB & ( LAB OR RAB )` 进行判断的，为了得到旋转后的物体状态（图中斜纹的A、B），我们需要从水平方向的两侧进行抓取，所以这时候我们需要物体左右的约束信息。如果只是要得到箱子的原始状态（图中实心颜色的A、B），我们只需要从它们的上方从上往下抓取，这时是不用考虑物体的LAB和RAB的，所以我们将其设置为0。

**Comment by tangarfff** [comment]
谢谢，我大概理解了。
还有一个问题是关于模型架构的。
我理解的是装箱的时候有三个目标，分别是选取箱子（select sequence），选取方向（select orientation）以及选取位置（select position）。
看您的方法是使用DRL来选取箱子和方向，选取位置的时候采用的是启发式算法。所以您训练的是一个多任务的网络没错吧？有两个task分别是箱子的sequence以及orientation。
关于模型的架构，如下图所示，您输出的Yt里是既包含了应该选的箱子的ID，以及应该选的orientation是吗？
![image](https://user-images.githubusercontent.com/77969537/120155728-bae2c600-c223-11eb-9675-7ad87aa958c6.png)

**Comment by Juzhan** [comment]
对，这个网络同时选择箱子ID和箱子的旋转状态，网络每次输出的yt只是一个下标数字，这个数字既包含了箱子的ID，也有它对应的旋转，比如图中网络训练的是n个2D箱子的setting，所以网络的输入有2n个状态，每次循环的时候输出的yt就是1~2n之间的一个数，yt除以2就是所选箱子的ID，yt是奇数就说明选择的是箱子的原始状态，偶数的话就是旋转状态。

**Comment by tangarfff** [comment]
理解了，谢谢！
