### ISSUE TITLE
论文里的可视化三维图像

### ISSUE THREAD

**Issue by github097** [Juzhan/TAP-Net#2]
尊敬的作者，您好：
       想请教您论文里可视化的三维图像，是如何运行的呢？在代码里可以复现的出来吗？
![image](https://user-images.githubusercontent.com/101797011/171594413-c7244d53-5863-4448-baa7-107170785fe3.png)
万分感谢了！

**Comment by Juzhan** [comment]
你好，我们在tools.py里面基于matplotlib实现了一个简单的三维装箱结果的绘制 [draw_container_voxel](https://github.com/Juzhan/TAP-Net/blob/6eded316d0b18c6fbec6cde31a53c34b8761c32a/tools.py#L284)，我们之前是自己用这个简单看一下装箱效果，但并不好看。我们论文中的结果图是使用3DMax手动渲染生成的。当初我们先用blender软件生成这些箱子的obj，导出后再用3DMax渲染的。
如果你是想用代码渲染出类似的效果，我建议你可以使用blender，它内部支持python，我这里有一些[blender示例代码](https://github.com/Juzhan/blender_tools)。你可以参考里面添加立方体的方法将这些三维的箱子数据用blender渲染出来。

**Comment by github097** [comment]
十分抱歉到现在才回复您的消息，谢谢您了，特别感谢您的悉心指导。

**Comment by Juzhan** [comment]
同学言重了😂，我只是回复了我们这个工作有关的问题而已，不用客气哈哈哈
