### ISSUE TITLE
对于encoder-decoder网络结构部分有点不太理解

### ISSUE THREAD

**Issue by wenjinghu** [Juzhan/TAP-Net#3]
您好，请问encoder-decoder图中的w^(t-1)具体指的是什么呢？我学习了一下解码器的原理，了解到每一个时间步的隐层节点都会有3个输入，分别是上一时间步的输出y^(t-1), 上下文变量c以及上一时间步的隐藏状态h^(t-1)，这里能否把w^(t-1)理解成上一时间步的隐藏状态h^(t-1)呢？w^(t-1)与注意力机制之间有输入输出的关系吗？谢谢大神的解答~ 
![image](https://user-images.githubusercontent.com/38206009/221164993-caa6e5ab-d111-4a27-a6e7-d3bb13f84220.png)

**Comment by Juzhan** [comment]
我们使用的RNN结构是GRU，这里有一些介绍：https://blog.csdn.net/ZhangJingHuaJYO/article/details/122415217

![image](https://user-images.githubusercontent.com/18376468/221328806-bd769fbb-b2e8-462e-874f-728f637924f8.png)

我们图中的w^(t-1)是就对应上面这个GRU中上一个时间步输出的隐藏状态h^(t-1)，当网络第一次执行的时候，我们没有上一步的隐藏状态，那时候输入的w^(t-1)会设置为空。

**Comment by wenjinghu** [comment]
理解了，非常感谢您的解答！
